CREATE TABLE TBL_MEMBER(
	/* PK : 중복되지 않고 NULL이 아닌 컬럼(제약조건) */
	MEMBER_ID VARCHAR2(100),
	MEMBER_PW VARCHAR2(100),
	CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_ID)
);
SELECT * FROM TBL_MEMBER;


INSERT INTO TBL_MEMBER (MEMBER_ID, MEMBER_PW) VALUES('shine94', '1234');
DELETE FROM TBL_MEMBER WHERE MEMBER_ID='shine94';